import numpy as np
import pandas as pd

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from data import courses, students,nov,dec,deliveries,ipl


# inner join

regs=pd.concat([nov,dec],axis=0,ignore_index=True)

# print(students.merge(regs,how="inner",on="student_id"))

# left join

# print(courses.merge(regs,how="left",on="course_id"))

# right join

temp_df=pd.DataFrame({
    'student_id': [26,27,28],
    'name': ['Rahul', 'Priya', 'Amit'],
    'partner': [28,26,17]
})

students=pd.concat([students,temp_df],axis=0,ignore_index=True)

# print(students.merge(regs,how="right",on="student_id"))

# outer join

# print(students.merge(regs,how="outer",on="student_id"))


# find total revenue generated by the company

total_revenue=regs.merge(courses,how="inner",on="course_id")["price"].sum()

# print(total_revenue)


# find revenue month by month

temp_df = (
    pd.concat([nov, dec], keys=["Nov", "Dec"])
      .reset_index()
      .rename(columns={"level_0": "month"})
)

monthly_revenue = (
    temp_df.merge(courses, on="course_id")
           .groupby("month")["price"]
           .sum()
)

# print(monthly_revenue)


# print the registration table
# cols -> name, -> course, -> price

# print(
#     regs.merge(students,on="student_id")
#         .merge(courses,on="course_id")
#         [["name","course_name","price"]]
# )


# plot a bar chart for revenue/course

# import matplotlib.pyplot as plt

# revenue_per_course = (
#     regs.merge(courses, on="course_id")
#            .groupby("course_name")["price"]
#            .sum()
# )
# revenue_per_course.plot(kind="bar")
# plt.show()


# find students who enrolled in both the monrths 
both_months = np.intersect1d(nov["student_id"], dec["student_id"])
# print(students[students['student_id'].isin(both_months)])


# find course that have no enrollments

no_enrollments = np.setdiff1d(courses["course_id"], regs["course_id"])
# print(courses[courses['course_id'].isin(no_enrollments)])


# find students who  did not enroll into any course

no_enrollments_students = np.setdiff1d(students["student_id"], regs["student_id"])
# print(students[students['student_id'].isin(no_enrollments_students)])


# self join
# find student name -> partner name for all enrolled students

students_with_partner = (
    students.merge(students, how="inner", left_on="partner", right_on="student_id", suffixes=("_student", "_partner"))
    [["name_student", "name_partner"]]
)
# print(students_with_partner)

# find top 3 students who did most numbers enrollments

top_students = (
    regs.merge(students, on="student_id")
        .groupby(["student_id", "name"])["course_id"]
        .count()
        .sort_values(ascending=False)
        .head(3)
)

# print(top_students)


# find top 3 students who spent most money on courses

top_spenders = (
    regs.merge(students, on="student_id")
        .merge(courses, on="course_id")
        .groupby(["student_id", "name"])["price"]
        .sum()
        .sort_values(ascending=False)
        .head(3)
)

# print(top_spenders)


# IPL Problems

# find top 3 stadiums whith highest sixes/match ratios

df = deliveries.merge(ipl, left_on="match_id", right_on="id")

top_stadiums = (
    df[df["batsman_runs"] == 6]
      .groupby("venue")
      .size()
      .div(df.groupby("venue")["match_id"].nunique())
      .sort_values(ascending=False)
      .head(3)
)

# print(top_stadiums)


# find orange cap holder of all the seasons


orange_cap = (
    df.groupby(["season", "batsman"], as_index=False)["batsman_runs"]
      .sum()
      .sort_values("batsman_runs", ascending=False)
      .drop_duplicates("season")
      .sort_values("season")
)

print(orange_cap)


